### ISSUE TITLE
Cannot add a picture with the new Compose UI

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#1082]
I can't seem to add pictures with the new compose UI. Every time I click to add any pictures nothing happens. I'm using Firefox 65.01 on 64-bit Linux Mint 19.1.

**Comment by asonix** [comment]
Here's the error I get

![image](https://user-images.githubusercontent.com/5304643/55033909-36acac80-4fe2-11e9-8380-16e4f6d79e9e.png)

Firefox 65.0.1 on Solus

**Comment by dansup** [comment]
This is fixed in the latest commits!

**Comment by asonix** [comment]
@dansup latest commits _where?_ I'm running the latest dev on pooltoy.club & still having this issue.

**Comment by ghost** [comment]
Still doesn't work. Doesn't work on Firefox Android 64 on Android 6 either. I've tried it on both pixelfed.social and pxlfd.me

**Comment by andre-dierker** [comment]
Same for me. Happens only with Firefox, Chrome is working.

**Comment by dansup** [comment]
@its3ch0 @asonix @andre-dierker Can you confirm this bug still exists?

**Comment by asonix** [comment]
It seems to be working with the latest version of pixelfed and firefox 66.0.1. Still broken on my phone running Fennec F-Droid 65.0.1 (firefox mobile).

It could be that the 65 -> 66 update fixes this issue.

**Comment by asonix** [comment]
Updated Fennec F-Droid to 66 and it works now.

**Comment by LiohMoeller** [comment]
Does not work with FF 60.6.3esr.
