### ISSUE TITLE
support multiple OAuth redirect URLs

### ISSUE THREAD

**Issue by snarfed** [pixelfed/pixelfed#2106]
hi all! one feature of Mastodon's OAuth that i depend on is support for multiple redirect URLs. when i register a Mastodon app with [`/api/v1/apps`](https://docs.joinmastodon.org/methods/apps/), i can pass multiple URLs into the `redirect_uris` parameter, separated by newlines, and Mastodon then lets me use any of them in a user-facing OAuth flow with my app.

(in Mastodon, this newline-separated `redirect_uris` support is provided by the Doorkeeper library: https://github.com/doorkeeper-gem/doorkeeper/pull/298)

when i try this with Pixelfed, it lets me register the app successfully, but when i then redirect a user to `/oauth/authorize` with that app and one of the redirect URLs, i get a 401 response with:

```json
{
  "error": "invalid_client",
  "error_description": "Client authentication failed",
  "message": "Client authentication failed"
}
```

if i register the app with just a single redirect URL, the same `/oauth/authorize` request works fine.

thanks in advance!

**Comment by snarfed** [comment]
thanks again for this fix! i'm not sure it's working in 0.10.9 on piconic though. i still see the same problem when i create an app with multiple newline-separated redirect uris, eg:

```
INFO:root:requests.post https://piconic.co/api/v1/apps {'data': 'client_name=Bridgy&redirect_uris=http%3A%2F%2Flocalhost%3A8080%2Fpixelfed%2Fcallback&website=http%3A%2F%2Flocalhost%3A8080&scopes=read+read%3Aaccounts+read%3Ablocks+read%3Afavourites+read%3Afilters+read%3Afollows+read%3Alists+read%3Amutes+read%3Anotifications+read%3Areports+read%3Asearch+read%3Astatuses+write+write%3Aaccounts+write%3Ablocks+write%3Afavourites+write%3Afilters+write%3Afollows+write%3Alists+write%3Amedia+write%3Amutes+write%3Anotifications+write%3Areports+write%3Astatuses+follow+push', 'headers': {'Content-Type': '...'}}
INFO:root:Got {'id': 157, 'name': 'Bridgy', 'website': None, 'redirect_uri': 'http://localhost:8080/pixelfed/callback', 'client_id': 157, 'client_secret': '...', 'vapid_key': None}
```

redirecting the user to this endpoint:

```
https://piconic.co/oauth/authorize?response_type=code&client_id=158&client_secret=...&scope=read%20read&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fpixelfed%2Fcallback&state={%22app_key%22:%22...%22,%22state%22:%22%257B%2522feature%2522%253A%2522listen%2522%252C%2522operation%2522%253A%2522add%2522%257D%22}
```

400s with:

```json
{"error":"invalid_client","error_description":"Client authentication failed","message":"Client authentication failed"}
```

when i use just one redirect uri though, it works fine:

```
INFO:root:requests.post https://piconic.co/api/v1/apps {'data': 'client_name=Bridgy&redirect_uris=http%3A%2F%2Flocalhost%3A8080%2Fdelete%2Ffinish%0Ahttp%3A%2F%2Flocalhost%3A8080%2Fpublish%2Fpixelfed%2Ffinish%0Ahttp%3A%2F%2Flocalhost%3A8080%2Fpixelfed%2Fcallback%0Ahttp%3A%2F%2Flocalhost%3A8080%2Fpixelfed%2Fdelete%2Ffinish&website=http%3A%2F%2Flocalhost%3A8080&scopes=read+read%3Aaccounts+read%3Ablocks+read%3Afavourites+read%3Afilters+read%3Afollows+read%3Alists+read%3Amutes+read%3Anotifications+read%3Areports+read%3Asearch+read%3Astatuses+write+write%3Aaccounts+write%3Ablocks+write%3Afavourites+write%3Afilters+write%3Afollows+write%3Alists+write%3Amedia+write%3Amutes+write%3Anotifications+write%3Areports+write%3Astatuses+follow+push', 'headers': {'Content-Type': '...'}}
INFO:root:Got {'id': 158, 'name': 'Bridgy', 'website': None, 'redirect_uri': 'http://localhost:8080/delete/finish\nhttp://localhost:8080/publish/pixelfed/finish\nhttp://localhost:8080/pixelfed/callback\nhttp://localhost:8080/pixelfed/delete/finish', 'client_id': 158, 'client_secret': '....', 'vapid_key': None}
```

**Comment by snarfed** [comment]
^ looks like @hnrd's commit here might do the trick? Any chance of getting this updated to current head (it's old, I know) and merged?

**Comment by kristofzerbe** [comment]
Asked again on https://github.com/snarfed/bridgy/issues/927#issuecomment-2028440023 regarding bridging Pixelfed, but @snarfed had to give me the known answer. It  would be so kind to address this bug and finding a solution. Can't wait the syndicate my Pixelfed posts the right way...

**Comment by kristofzerbe** [comment]
Hi ... it's bin a while since I asked for a solution of this issue. @snarfed has mentioned a possible fix in Nov 2022. Has anyone verified this? @dansup?  It would be wonderful if Pixelfed was able to send webmentions via Bridgy, as it already works with Flickr. I syndicate my photos to Pixelfed, but the way back to display the reactions on my website is blocked.

**Comment by dansup** [comment]
@kristofzerbe @snarfed We've fixed a lot of the OAuth issues, including the ones mentioned and others like adding a few [fine grained scopes](https://pixelfed.social/oauth/scopes) 

```json
[
  {
    "id": "read",
    "description": "Full read access to your account"
  },
  {
    "id": "write",
    "description": "Full write access to your account"
  },
  {
    "id": "follow",
    "description": "Ability to follow other profiles"
  },
  {
    "id": "admin:read",
    "description": "Read all data on the server"
  },
  {
    "id": "admin:read:domain_blocks",
    "description": "Read sensitive information of all domain blocks"
  },
  {
    "id": "admin:write",
    "description": "Modify all data on the server"
  },
  {
    "id": "admin:write:domain_blocks",
    "description": "Perform moderation actions on domain blocks"
  },
  {
    "id": "push",
    "description": "Receive your push notifications"
  }
]
``` 

and fixing oob support in https://github.com/pixelfed/pixelfed/pull/5413

Can you let me know if there are any other bugs you are aware of regarding OAuth or the APIs?

**Comment by dansup** [comment]
I just shipped a CORS and CSRF bugfix, I can now generate the access/refresh tokens using the oob flow!

## Authorization Flow

### 1. Generate Authorization URL

Create an authorization URL with your client_id:

```
https://pixelfed.social/oauth/authorize?client_id=YOUR_CLIENT_ID&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=read+write
```

### 2. User Authorization Steps

1. Direct the user to the authorization URL
2. User logs into their Pixelfed account
3. User approves your application's access request
4. Pixelfed displays an authorization code to the user

### 3. Exchange Code for Access Token

Once you have the authorization code, exchange it for an access token:

```bash
curl -X POST -H "Content-Type: application/json" \
  'https://pixelfed.social/oauth/token' \
  -d '{
    "client_id": "YOUR_CLIENT_ID",
    "client_secret": "YOUR_CLIENT_SECRET",
    "code": "AUTHORIZATION_CODE",
    "redirect_uri": "urn:ietf:wg:oauth:2.0:oob",
    "grant_type": "authorization_code"
  }'
```

The server will respond with your access token:

```json
{
  "access_token": "YOUR_ACCESS_TOKEN",
  "token_type": "Bearer",
  "scope": "read write",
  "expires_in": 31536000,
  "created_at": 1577836800
}
```

## Using the Access Token

Make authenticated API requests using the Bearer token:

```bash
curl -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \
  'https://pixelfed.social/api/v1/accounts/verify_credentials'
```

## Important Notes

- Replace placeholder values (`YOUR_CLIENT_ID`, `YOUR_CLIENT_SECRET`, etc.) with your actual credentials
- The `urn:ietf:wg:oauth:2.0:oob` redirect URI specifies an out-of-band flow
- Store access tokens securely
- Be prepared to handle token expiration and refresh flows
- Some endpoints may require specific headers like `X-Requested-With: XMLHttpRequest`

**Comment by snarfed** [comment]
Hey @dansup, thanks for the fixes and updates here! I'm still seeing the failure with multiple redirect URIs in the original issue description here though. I'm testing against pixelfed.social, have the fixes been deployed there?

**Comment by dansup** [comment]
@snarfed It was a urlencoding issue 😅 The fix has been deployed to pixelfed.social, I tested it successfully with

```
curl -X POST -H "Content-Type: application/json" \
  'https://pixelfed.social/api/v1/apps' \
  -d '{
    "redirect_uris": "urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob,https%3A%2F%2Floopd.test%2Fcallback",
    "client_name": "Pixelfed"
  }'
  ```

Can you confirm?

**Comment by snarfed** [comment]
@dansup woo, success! Working for me now. Thank you!
