### ISSUE TITLE
[Bug] /account/activity loads Error page

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#235]
Whoops, looks like something went wrong.

https://pixelfed.social/account/activity

![image](https://user-images.githubusercontent.com/10606431/41127890-ed47e6b4-6a71-11e8-80cd-51adef7fd0a6.png)

**Comment by dansup** [comment]
Fixed in latest commits

**Comment by trwnh** [comment]
Still happening, but also still only on `trwnh` and not other accounts. Same 500 error. Per earlier conversation on IRC, I suggested that it might be because I had deleted posts that had been liked before.

**Comment by trwnh** [comment]
Still happening, almost certainly due to likes/comments on deleted posts.

**Comment by trwnh** [comment]
No longer seeing this issue!
