### ISSUE TITLE
ErrorException: Undefined index: attributedTo in ..pixelfed/app/Util/ActivityPub/Helpers.php:317

### ISSUE THREAD

**Issue by jk-na** [pixelfed/pixelfed#2572]
Since latest code merge I have what appears to be a new failed horizon job:

`ErrorException: Undefined index: attributedTo in /usr/share/nginx/html/pixelfed/app/Util/ActivityPub/Helpers.php:317`

Full stacktrace: https://pastebin.com/iA5cdLQb

**Comment by dansup** [comment]
Fixed in v0.10.10

**Comment by jk-na** [comment]
I'm still seeing these errors on my horizon failed jobs page.. I'm up-to-date with commits.
