### ISSUE TITLE
Pixeldroid does not connect

### ISSUE THREAD

**Issue by AnonymousWebHacker** [pixelfed/pixelfed#2709]
It seems to me that in the pixelfed configuration, some permission or something must be added to allow it to log in to the android apk

**Comment by joni1993** [comment]
You need to Set  `OAUTH_ENABLED=true` and run `php artisan passport:keys`.
Don't forget to clear the Caches afterwards.

**Comment by kaluaim** [comment]
For more info about **Authorization** https://docs.pixelfed.org/technical-documentation/api-v1.html#authorization

**Comment by AnonymousWebHacker** [comment]
Solved. 
I had added OAUTH_ENABLED = true in the .env but had not cleared the cache XD
Thank you both very much for your reply. @kaluaim @joni1993

**Comment by AnonymousWebHacker** [comment]
> 
> 
> For more info about **Authorization** https://docs.pixelfed.org/technical-documentation/api-v1.html#authorization

My God, it is more than clear there, and I never gave myself to do a search in the official documentation, thinking that they did not deal with that subject.
Tnks men

**Comment by aarontrom** [comment]
Thanks a lot for these tips, but somehow I still can't upload pictures from Pixeldroid to my Pixelfed-Instance...
I did exactly these steps: https://docs.pixelfed.org/technical-documentation/api-v1.html#authorization
and I also cleared the cache... 
I connected Pixeldroid with Pixelfed as you can see here:

![Pixelfed](https://user-images.githubusercontent.com/69819346/152234567-7b219207-b9a9-4a8f-b3c2-17312038e13f.jpg)

but every time I upload a picture, I get the following error:

![Pixeldroid](https://user-images.githubusercontent.com/69819346/152236310-c3efe257-23ff-4887-9dd2-a2adc19c5e12.jpg)

Does anyone know, what I could try?

Thanks in advance

**Comment by joni1993** [comment]
It may be a permission issue or something like that.
Error 500 should produce some logs, what does the log say?

**Comment by aarontrom** [comment]
Do you mean the logs in yunohost?
I don't get anything there related with Pixelfed: 
![yunohost logs](https://user-images.githubusercontent.com/69819346/152249356-111f63f0-9ecc-476d-9675-170e76043801.jpg)

can I get some logs of pixeldroid also by checking with a command in the terminal when connected with my server? 

btw here are infos about my instance: 
 
### Instance Diagnostic 
Version: 0.11.1
PHP: 7.3.31-1~deb10u1
PHP-bcmath: Installed
PHP-ctype: Installed
PHP-curl: Installed
PHP-intl: Installed
PHP-json: Installed
PHP-mbstring: Installed
PHP-openssl: Installed
PHP-redis: Installed
Database: pgsql (11.14)
Bootstrap: Writable
Storage: Writable
========= END =========

and I'm also running yunohost on the latest version 4.3.6.2 (stable)

**Comment by aarontrom** [comment]
btw I just saw that thread: https://github.com/pixelfed/pixelfed/pull/3041 - so it would be good to upgrade PHP from 7.3.31-1 to 7.4 at least I guess... 
But is that related to the error or not?

**Comment by joni1993** [comment]
Probably not.

Try checking the logs at storage/logs/ inside your pixelfed directory on the server.

**Comment by aarontrom** [comment]
Wow, there are many!
[laravel.log](https://github.com/pixelfed/pixelfed/files/7990580/laravel.log)
but they also repeat themselves. I have no idea about that and what creates these^^

**Comment by joni1993** [comment]
You are running an old version. This has already been fixed here: https://github.com/pixelfed/pixelfed/commit/b1678736328667e21be8e8fb5a51b48da1187a6a#diff-8e3ad3d5c548b79b00f6f03fe342057b0141eaa0f1d629d86df8d3b7447ac86d

**Comment by aarontrom** [comment]
Hm, I did the changes to the AdminStatsService.php file according to the link you provided, but that didn't really fix it. I am investigating and trying to figure it out :D thanks a lot for your help so far :+1:
