### ISSUE TITLE
Basic features don’t work (Direct messages and filters no longer work)

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#2729]
When trying to send a direct message it appears the admin of the instance is unable to send the message nor does a user is able to send a direct message to another user but a user can only send a direct message to the first admin that too lands in filtered messages and cannot be opened else the link breaks as the following image.

when attempted to open the filtered message or when a user is trying to send to direct message another user the following errors shows up page is broken

(simply a user cannot send a direct message to another user)

![C759ACFA-B25E-4AFE-ADDF-A1AE5579679E](https://user-images.githubusercontent.com/75223599/114793786-ca5b9c00-9da8-11eb-9977-46bd299ee214.jpeg)

![0C3A1D26-A8C4-4833-836E-BA8A965A4A19](https://user-images.githubusercontent.com/75223599/114793791-cdef2300-9da8-11eb-92a4-37dc7de8d8ba.jpeg)

Filters don’t apply either see the following image attached

![6D6A809C-7905-4A5B-BD6B-E8C5F9F0560D](https://user-images.githubusercontent.com/75223599/114794057-5077e280-9da9-11eb-8b75-26216493eb32.jpeg)
![7DC7BC65-B4E1-4115-8DAE-28BC8EAB07A8](https://user-images.githubusercontent.com/75223599/114794065-52da3c80-9da9-11eb-834d-8a986120d814.jpeg)
![E5171BC6-F61A-45F3-9D47-86183D1F372D](https://user-images.githubusercontent.com/75223599/114794066-5372d300-9da9-11eb-9e97-44c77000d485.jpeg)
![113B12EE-8613-4909-A885-D3A788CAE57E](https://user-images.githubusercontent.com/75223599/114794068-540b6980-9da9-11eb-8c43-9927c19a16a8.jpeg)

Post editing link is broken as well see the following attached 

![0A6614C2-2933-46B8-83E3-D33B6912E101](https://user-images.githubusercontent.com/75223599/114794169-82894480-9da9-11eb-8432-0b0705654fa5.jpeg)
![D9C16F26-5163-44C3-A11F-4A661DC409D7](https://user-images.githubusercontent.com/75223599/114794173-861ccb80-9da9-11eb-8a59-b538ea03c884.jpeg)

**Comment by ghost** [comment]
Here is a forum thread at cloudron with regards to the issue https://forum.cloudron.io/topic/4877/direct-messages-no-longer-work/15

This issue is not resolved or answered by pixelfed developers yet

**Comment by stelzch** [comment]
I was able to reproduce this issue within a docker container, and I think I know why it is happening.

In [these lines](https://github.com/pixelfed/pixelfed/blob/4ad3de3b885b8d21a53ca9cc8a4a83e2a1d4a459/app/Http/Controllers/AccountController.php#L129-L132) in the account controller, the following SQL query is generated:

```php
[2021-05-10 21:41:58] local.DEBUG: array (
  0 => 
  array (
    'query' => 'select * from `profiles` where `id` != ? and `profiles`.`id` = ? and `profiles`.`deleted_at` is null limit 1',
    'bindings' => 
    array (
      0 => 297440899045134336,
      1 => '297465207490482176',
    ),
    'time' => 37.91,
  ),
)
```

As you can see, the `id` in the URL gets treated as string and that's why the query does not return any results.

I will try to fix up a patch soon.

**Comment by stelzch** [comment]
I was able to reproduce the direct message issue within a docker container, and I think I know why it is happening.

In [these lines](https://github.com/pixelfed/pixelfed/blob/4ad3de3b885b8d21a53ca9cc8a4a83e2a1d4a459/app/Http/Controllers/AccountController.php#L129-L132) in the account controller, the following SQL query is generated:

```php
[2021-05-10 21:41:58] local.DEBUG: array (
  0 => 
  array (
	'query' => 'select * from `profiles` where `id` != ? and `profiles`.`id` = ? and `profiles`.`deleted_at` is null limit 1',
	'bindings' => 
	array (
	  0 => 297440899045134336,
	  1 => '297465207490482176',
	),
	'time' => 37.91,
  ),
)
```

As you can see, the `id` in the URL gets treated as string and that's why the query does not return any results.
I made a preliminary patch on [this branch](https://github.com/stelzch/pixelfed/tree/fix/dms) with int casts wherever necessary and it resolves the issue locally, but there must be some sort of underlying issue that needs to be investigated to tell why this stopped working.

**Comment by ghost** [comment]
Thank you for your patch and concern,
I’m running pixelfed and unable to direct message yet is there an estimated time for the update release?
>

**Comment by stelzch** [comment]
@deez17
Ultimately that depends on the maintainers, but it will likely take a few weeks at the very least.
You can test out the patch today, however I would not recommend using it in production.

**Comment by ghost** [comment]
Hello,


Thank yo try for your reply 
For your information I’m using pixelfed through cloudron it’s too complicated to install pixelfed raw installation. Through cloudron we are not able to patch or modify except the env file.

I wonder how is direct message working in this site >> pixelfed.social ? I registered and logged in tried direct messaging and it works fine. But not on the installation I installed through cloudron.

>

**Comment by stelzch** [comment]
That I do not know either, I'm guessing there is some software component (Pixelfed, PHP, Laravel Framework, MySQL, …) that is on another version.

Are you using v0.10.10 or the dev branch? I tried reproducing the issue in the dev branch.

**Comment by ghost** [comment]
Hello,

Thank you for your reply I’m using the following pixelfed app through cloudron  

https://www.cloudron.io/store/org.pixelfed.cloudronapp.html

**Comment by ghost** [comment]
Check the following link

https://forum.cloudron.io/category/90/pixelfed

**Comment by stelzch** [comment]
Ok, seems they are running v0.10.10

**Comment by ghost** [comment]
Pixelfed updates are too slow and I’m really annoyed with it I wonder how does direct messaging only work on pixelfed.social

**Comment by gramakri** [comment]
> Ok, seems they are running v0.10.10

I am the cloudron app packager. I have tried using the latest dev branch as well but I see different errors now which I reported in #2752

**Comment by gramakri** [comment]
>  I made a preliminary patch on [this branch](https://github.com/stelzch/pixelfed/tree/fix/dms) with int casts wherever necessary and it resolves the issue locally, but there must be some sort of underlying issue that needs to be investigated to tell why this stopped working.

I think @deez17 was saying that he doesn't see some of these issues in pixelfed.social site. I wonder if these are related to the underlying database? On Cloudron, we use MySQL. Per the docs, MySQL, MariaDB and PostgreSQL are supported. @dansup Can you tell us what database you primarily test with (and I can switch the Cloudron app package db accordingly, if that helps).

**Comment by dansup** [comment]
@gramakri I'm using MySQL. 

@deez17 Assuming cloudron has updated to v0.11.0 this issue should be resolved.

**Comment by ghost** [comment]
It’s not fixed yet if you see my site 
https://spacemag.xyz 

the drop down list of a user name 
doesn’t even appear like before 

![Uploading 490E8BA6-E9E1-49E4-98FC-4E302A88132E.jpeg…]()

**Comment by ghost** [comment]
@gramakri @dansup 

Girish please look into this ?

still getting sorry this page isn’t available error
