### ISSUE TITLE
Some admin settings are not saved

### ISSUE THREAD

**Issue by benhartwich** [pixelfed/pixelfed#2801]
Hi,

I´ve installed Pixelfed at Debian 10 with php7.3, nginx and mariadb. When I try to save the short description, about title and e.g. about page - it´s reseted to the default text. What can possibly go wrong? App debug doesn´t show any infos.

**Comment by dansup** [comment]
Do you have `opcache` enabled in `php.ini`?

**Comment by benhartwich** [comment]
Nope.

**Comment by dansup** [comment]
Have you tried restarting php-fpm?

**Comment by Valinwolf** [comment]
I am also having this issue. It's only some settings, not all. I had opcache enabled, so I tried disabling it for the fpm pool used by pixelfed. No change after restarting php-fpm or disabling opcache.

**Comment by aarontrom** [comment]
I also tried to save some custom css settings, but every time I try to save them, they do not get saved... 
Any tips on how to solve that?

I have "ENABLE_CONFIG_CACHE=true" in the .env file and I'm running Pixelfed v0.11.1 on yunohost 4.3.6.2 (stable).

**Comment by stephen304** [comment]
I was having this issue with the max album size - the confusing thing about `ENABLE_CONFIG_CACHE` is that after changing settings in the admin panel, if you turn off `ENABLE_CONFIG_CACHE`, you no longer can access the admin settings panel but the settings that you changed still supersedes the .env file. I was unable to enable registration again through the env file after disabling it through the admin panel while `ENABLE_CONFIG_CACHE` - I'm sure I ran `php artisan config:cache` after changing settings.

**Comment by Gxnfvhg** [comment]
Go to the folder where you installed Pixelfed and set the permissions to 775, it fixed the problem for me.

**Comment by aarontrom** [comment]
> Go to the folder where you installed Pixelfed and set the permissions to 775, it fixed the problem for me.

@Gxnfvhg can you specify the folder and file where to do that exactly?

**Comment by Gxnfvhg** [comment]
If i remember correctly, it should be storage/framework/views but it seems like i've applied it to my entire pixelfed folder... So maybe it's not the best solution...

**Comment by azbulutlu** [comment]
setting storage/framework/views to 775 works to help saving some branding options, not about page and not CSS though. Also ran into the same issue using 11.2 on yunohost.

**Comment by lapineige** [comment]
This seems to be a quite frequent issue with Yunohost users. As described [here](https://github.com/YunoHost-Apps/pixelfed_ynh/issues/172#issuecomment-1100894607), until we fix this on the Yunohost app, this command should fix it `sudo chmod 600 /var/www/pixelfed/.env` (please confirm if it does).

**Comment by aarontrom** [comment]
hi @lapineige thanks for the help! I tried that command but the issue persists.
