### ISSUE TITLE
Add "follow" / "unfollow" to overflow menu of post permalinks

### ISSUE THREAD

**Issue by qwazix** [pixelfed/pixelfed#293]
For new users, following sufficient number of users so that their timeline updates reasonably quickly is a tedious process especially on mobile.

You have to go to the public timeline, click the username of the person whose photo you like, tap follow and then go back to the previous page. Due to the infinite scroller you have now lost your position on the list (at least on mobile) and you have to scroll back to your old position all over again.

I would suggest a follow button next to the username or some other interaction (double-tap the avatar or something to follow. This could be shown as a hint on first visit) to make following users whose photos you like easier.

**Comment by trwnh** [comment]
This isn't unique to public timelines -- it should be possible to un/follow people wherever you can see their posts.

**Comment by dansup** [comment]
Moving to v0.12 due to the significant amount of refactoring required for this

**Comment by dansup** [comment]
Fixed in latest commits

**Comment by trwnh** [comment]
Not actually fixed yet, unless you consider it only for timelines and not for posts themselves 
![image](https://user-images.githubusercontent.com/10606431/66249225-75d85a80-e6f5-11e9-9c90-da35dcf8eadf.png)

**Comment by dansup** [comment]
@trwnh Yes, for timelines only. If it was available for posts, it should be available on comment permalinks and other status pages which it currently is not.

**Comment by trwnh** [comment]
> If it was available for posts, it should be available on comment permalinks and other status pages which it currently is not.

I don't see why we shouldn't do that as well.
