### ISSUE TITLE
[Bug] Liking your own post causes uncaught 500 error in promise

### ISSUE THREAD

**Issue by trwnh** [pixelfed/pixelfed#337]
### Error screenshot

![image](https://user-images.githubusercontent.com/10606431/43120204-03261b9a-8edf-11e8-9f91-e6d0214d51e2.png)

### Steps to reproduce:
1) Like your own post (from anywhere -- timeline or profile)

### Expected behavior:
2) Post is successfully liked

### Actual behavior:
2) Like fails with 500 error

### Logs
```
POST https://pixelfed.social/i/like 500
  (anonymous)            @ app.js?id=4c24407...:1
  t.exports              @ app.js?id=4c24407...:1
  t.exports              @ app.js?id=4c24407...:1
  Promise.then (async)
  XmWM.a.request         @ app.js?id=4c24407...:1
  a.(anonymous function) @ app.js?id=4c24407...:1
  (anonymous)            @ app.js?id=4c24407...:1
  (anonymous)            @ app.js?id=4c24407...:1
  dispatch               @ app.js?id=4c24407...:1
  v.handle               @ app.js?id=4c24407...:1
```
```
Uncaught (in promise) Error: Request failed with status code 500
    at FtD3.t.exports (app.js?id=4c24407...:1)
    at t.exports (app.js?id=4c24407...:1)
    at XMLHttpRequest.p.(anonymous function) (https://pixelfed.social/js/app.js?id=4c24407...1:8893)
  FtD3.t.exports         @ app.js?id=4c24407...:1
  t.exports              @ app.js?id=4c24407...:1
  p.(anonymous function) @ app.js?id=4c24407...:1
  Promise.then (async)
  (anonymous)            @ app.js?id=4c24407...:1
  dispatch               @ app.js?id=4c24407...:1
  v.handle               @ app.js?id=4c24407...:1
```

**Comment by dansup** [comment]
@trwnh Fixed in latest commits!

**Comment by trwnh** [comment]
@dansup not fully fixed for me. At this point, I'm starting think with all the 500 errors that there's something wrong specifically with the account pixelfed.social/trwnh (and maybe others). I still get 500 errors when attempting to like my own posts, when attempting to load notifications, and when attempting to load permalinks of some comments. Not sure at all what is causing this...

EDIT: nvm, it's not "uncaught promise" anymore. Guess it's a separate issue, most likely https://github.com/pixelfed/pixelfed/issues/221#issuecomment-414159073
