### ISSUE TITLE
Enabling cloud storage breaks user profile avatar url

### ISSUE THREAD

**Issue by okpierre** [pixelfed/pixelfed#3559]
Pixelfed https://github.com/pixelfed/pixelfed/commit/76dbddfae9cf26ba1937810f1ecd791e41f5b7c6

Enabling s3 will break user profile avatars

local URL for images: working
local URL for avatars: working

**cloud** URL for images: working 
**cloud** URL for avatars: broken 

** it seems url is appended to existing one - see below

For example:
```
url for images = https://cdn.pixelfed.test/public/m/_v2/1/xxx

url for avatars = https://pixelfed.testhttps://cdn.pixelfed.test/public/m/_v2/1/xxx
```

**Comment by okpierre** [comment]
Hi @dansup does this commit fix issue above? https://github.com/pixelfed/pixelfed/commit/672f7c8c

**Comment by sir-octopus** [comment]
I'm currently up to date with dev and experiencing this issue. I get the default avatar image everywhere at /i/web but at /settings/home I get an image with a malformed source like this:
`https://my-redacted-domain.comhttps://my-redacted-cloud-storage.com/pixelfed-bucket-20220728-1330/public/avatars/046/211/443/849/321/677/2/uu1zCsXDguuGj5I2nAUE_avatar.jpg?v=2`

It looks like the cdn_url field in the avatars table isn't being populated. When I put the correct full URL there manually, and run php artisan cache:clear, my avatar turns up as expected.

**Comment by dansup** [comment]
@okpierre Yes, confirmed fixed in https://github.com/pixelfed/pixelfed/commit/672f7c8c! You may need to run `php artisan cache:clear` after updating

**Comment by mackiexx** [comment]
I followed the fix and now the profile photo is broken but the feeds still shows photo when you post. i am using aws s3 cloud storage. looking at the dev console, it shows 

<img draggable="false" onerror="this.onerror=null;this.src='/storage/avatars/default.png?v=0';" class="avatar shadow cursor-pointer">

**Comment by mackiexx** [comment]
i recently started my website which was yesterday but this problem still occurs on my website. i cloned directly from here and i thought the change was committed already. this hasnt been solved?

**Comment by foozmeat** [comment]
Hi I've got a new install running v0.11.4 and I'm seeing the exact same malformed URLs as above. I tried clearing my cache but there was no change.

**Comment by okpierre** [comment]
@mackiexx @foozmeat this is still an issue with the latest installation https://github.com/pixelfed/pixelfed/commit/92dd5b9abf5693e9c838211e40f54551f3fc96cc

I'm unable to reopen this issue @dansup

**Comment by foozmeat** [comment]
For the record I'm using the DO Spaces config:

```env
FILESYSTEM_DRIVER=spaces
FILESYSTEM_CLOUD=spaces
PF_ENABLE_CLOUD=True
DO_SPACES_KEY=key
DO_SPACES_SECRET=secret
DO_SPACES_ENDPOINT=https://sfo3.digitaloceanspaces.com
DO_SPACES_REGION=sfo3
DO_SPACES_BUCKET=bucket
```

Here's the HTML rendered on the account settings screen
```html
<img src="https://buckethttps://bucket.sfo3.digitaloceanspaces.com/public/avatars/default.jpg%3Fv%3D4" width="38px" height="38px" class="rounded-circle float-right">
```

**Comment by hskrasek** [comment]
For anyone still having an issue with this, it seems that avatar uploads are not properly setting the cdn_url property. I had to change the following lines https://github.com/pixelfed/pixelfed/blob/dev/app/Profile.php#L177-L179 to this:

```php
return Storage::url($path) . "?v={$avatar->change_count}";
```

**Comment by MarkoKaartinen** [comment]
> For anyone still having an issue with this, it seems that avatar uploads are not properly setting the cdn_url property. I had to change the following lines https://github.com/pixelfed/pixelfed/blob/dev/app/Profile.php#L177-L179 to this:
> 
> ```
> return Storage::url($path) . "?v={$avatar->change_count}";
> ```

Thanks. This fixed it for me. But updating will break this change so it would be great to have this fixed 👍🏻

**Comment by okpierre** [comment]
dansup said this is a configuration issue see this post https://github.com/pixelfed/pixelfed/issues/3845#issuecomment-1328669310

His suggestion ... give this a try:
```
Make sure you don't have AWS_URL set in .env, and if PF_ENABLE_CLOUD=false 
you can use REMOTE_AVATARS=true to store them locally (otherwise with 
PF_ENABLE_CLOUD they are stored on cloud fs).

Remember to run php artisan config:cache && php artisan cache:clear after editing .env.
```
