### ISSUE TITLE
Links to photos in federated posts are broken

### ISSUE THREAD

**Issue by SteveDinn** [pixelfed/pixelfed#4403]
When I view a post using my Pixelfed account, the images show properly.
![Screenshot_20230522-160324](https://github.com/pixelfed/pixelfed/assets/3911507/01b1b5cd-c1dc-4f4a-bde3-90a7626a42b3)

But when I view the same post from my mastodon account, I cannot see the photos. Clicking on them shows the photo from the Pixelfed server correctly. It just doesn't show up in the federated post. Screenshots from Tusky and Mastodon web client. 
![image](https://github.com/pixelfed/pixelfed/assets/3911507/6e26d6f2-f4eb-43f5-a7d8-124d4105919a)
![Screenshot_20230522-161401](https://github.com/pixelfed/pixelfed/assets/3911507/2d811765-479d-4fdb-88b8-977097db6327)

Pixelfed version information:
![Screenshot_20230522-160729](https://github.com/pixelfed/pixelfed/assets/3911507/369080b1-379b-4ce5-9d86-cd0daa97696d)

**Comment by SteveDinn** [comment]
This has happened in a change since May 15th. My last post was then, and the photos came across fine.

**Comment by SteveDinn** [comment]
Hrmm... After some investigation, this might be because I had split DNS entries for my pixel fed domain name, with my internal DNS pointing to my local (NAT) IP for my pixelfed server. I've reverted that change and made a test post and things seem to work.

I'm not sure how pixelfed works internally but I don't think that should break things. 

Seems like it's always DNS...

**Comment by dansup** [comment]
Fixed in #4404

**Comment by SteveDinn** [comment]
@dansup I'm on a build as of [this commit](https://github.com/pixelfed/pixelfed/commit/97ce98b2347ae9ba6469f1cace98ffe13ede2405), but this issue is not actually fixed, at least not in my use case.

I have a internal DNS server pointing directly at the private IP address for my pixelfed web server, which is behind my reverse proxy. The site itself works fine, it's just the references to the images that get posted that do not work.

Hit me up if you need more information about this use case.
