### ISSUE TITLE
Posts From Remote Account Not Showing

### ISSUE THREAD

**Issue by fishcharlie** [pixelfed/pixelfed#5294]
### Discussed in https://github.com/pixelfed/pixelfed/discussions/5271

<div type='discussions-op-text'>

<sup>Originally posted by **fishcharlie** August 19, 2024</sup>
I followed an account on my Pixelfed account and their posts are not showing up. I understand that previous posts shouldn't show up, and only posts after you follow the account will show up, but even newer posts after I followed aren't showing up.

I tried unfollowing the account and re-following, with no success. (You can even see my account in the followers tab on the remote account).

Not even sure how to begin to debug this. Any ideas would be appreciated.

<img width="1452" alt="Screenshot 2024-08-19 at 12 25 45 PM" src="https://github.com/user-attachments/assets/b8a386e9-af25-4c73-9b2e-9bdd10d439e2">
<img width="1436" alt="Screenshot 2024-08-19 at 12 25 59 PM" src="https://github.com/user-attachments/assets/b0a2cedb-2b47-4967-9a8f-8f91c42537d0">

https://botsin.space/@nasa_bot

**Edit** It looks like there is a request from the remote server that came in for the latest post.

```
app-1     | 2024-08-28T10:30:24.153503749Z 172.19.0.1 - - [28/Aug/2024:10:30:24 +0000] "POST /f/inbox HTTP/1.1" 200 359 "-" "http.rb/5.1.1 (Mastodon/4.2.10; +https://botsin.space/)"
```

Why would Pixelfed not be handling this properly?</div>

**Comment by fishcharlie** [comment]
Converted this into an issue since there is no indiction that it's anything other than a bug in pixelfed. Hopefully @dansup can fix this soon. I'd attempt to investigate further, but haven't worked with PHP in ages.

**Comment by dansup** [comment]
Working on a fix, this is a postgres bug.

**Comment by S0yKaf** [comment]
Any updates? This is pretty major. 

If lack of  time is the issue, I'd be willing to help fix this provided I get some pointers to get me started.

**Comment by fishcharlie** [comment]
@S0yKaf, @dansup said he'd work on this and that a fix will be released on [September 12th](https://mastodon.social/@dansup/113127102186897888). But since then he [hasn't replied to me](https://mstdn-social.com/@fishcharlie/113194426462876232).

Seems like he is more focused on Loops than sticking to his major commitments he made on Pixelfed, which is pretty frustrating.

I'd also help on this, but I have barely worked with PHP at all, so probably can't help that much.

**Comment by dansup** [comment]
@fishcharlie I'm having trouble reproducing this on pixelfed.social, the profile is loading fine, its likely a misconfiguration on your end.

![Screenshot 2024-12-22 at 2 23 44 PM](https://github.com/user-attachments/assets/c0555823-547d-4afa-b0bf-59b046a0a64c)

Please post the diagnostics from Admin -> Diagnostics

**Comment by fishcharlie** [comment]
@dansup I emailed you diagnostics on September 12th. 3 minutes before you said that it's a Postgres bug: https://github.com/pixelfed/pixelfed/issues/5294#issuecomment-2347391802. I'm confused why you'd say that so confidently if you still need diagnostics and other help debugging it? You sounded 100% sure you knew exactly what the issue is. You said you were already working on a fix. Now you say you can't reproduce it? I'm really confused.

**Comment by S0yKaf** [comment]
@dansup here's the Diagnostic on my end.
```
=======================
 Pixelfed Instance Diagnostic v0.2 
=======================
Troubleshooting

Bootstrap: Writable ✅
Storage: Writable ✅
DATABASE Ping: Pong! Connected to DB "pixelfed" ✅
REDIS Ping: Pong! Connected to Redis ✅
ACTIVITYPUB instance actor created: ✅ true
ACTIVITYPUB instance actor cached: ✅ true
OAUTH enabled: ✅ true
OAUTH token_expiration 365 days
OAUTH public key exists: ✅ true
OAUTH private key exists: ✅ true

Important Information

Version: 0.12.3-unknown git commit
Database: pgsql (16.2)
APP_URL: https://pix.canadiancivil.com
APP_DOMAIN: pix.canadiancivil.com
ADMIN_DOMAIN: pix.canadiancivil.com
SESSION_DOMAIN: pix.canadiancivil.com

PHP Variables

PHP: 8.3.9
PHP INI memory_limit: 128M
PHP INI post_max_size: 61M
PHP INI upload_max_filesize: 61M
PHP INI max_file_uploads: 4
PHP INI max_execution_time: 600
PHP INI max_input_time: 60
PHP INI file_uploads (On): 1
PHP INI - SECURITY allow_url_fopen (true): 1
PHP INI - SECURITY allow_url_include (false):
PHP INI - SECURITY expose_php (false):
PHP INI - SECURITY display_errors (false): Off
PHP INI - SECURITY display_startup_errors (false):
PHP INI - SECURITY log_errors (true): 1
PHP INI - SECURITY ignore_repeated_errors (false):
PHP INI - SECURITY disable_functions:

Pixelfed Variables (No Secrets)

CONFIG	VARIABLE NAME	DETAILS
APP	APP_NAME	"pixelfed"
APP	APP_ENV	"production"
APP	APP_DEBUG	❌ false
APP	APP_URL	"https://pix.canadiancivil.com"
APP	APP_LOCALE	"en"
APP	APP_FALLBACK_LOCALE	"en"
BROADCASTING	BROADCAST_DRIVER	"redis"
CACHE	CACHE_DRIVER	"redis"
CAPTCHA	CAPTCHA_ENABLED	❌ false
DATABASE	DB_CONNECTION	"pgsql"
DATABASE	REDIS_CLIENT	"predis"
EXP	EXP_LC	❌ false
EXP	EXP_TOP	❌ false
EXP	EXP_POLLS	❌ false
EXP	EXP_CPT	❌ false
EXP	EXP_GPS	❌ false
EXP	EXP_EMC	✅ true
FEDERATION	ACTIVITY_PUB	✅ true
FEDERATION	AP_OUTBOX	✅ true
FEDERATION	AP_INBOX	✅ true
FEDERATION	AP_SHAREDINBOX	✅ true
FEDERATION	AP_REMOTE_FOLLOW	✅ true
FEDERATION	ACTIVITYPUB_DELIVERY_TIMEOUT	"30"
FEDERATION	ACTIVITYPUB_DELIVERY_CONCURRENCY	"10"
FEDERATION	AP_LOGGER_ENABLED	❌ false
FEDERATION	ATOM_FEEDS	✅ true
FEDERATION	REMOTE_AVATARS	✅ true
FEDERATION	NODEINFO	✅ true
FEDERATION	WEBFINGER	✅ true
FEDERATION	PF_NETWORK_TIMELINE	✅ true
FEDERATION	PF_NETWORK_TIMELINE_DAYS_FALLOFF	90
FEDERATION	CUSTOM_EMOJI	❌ false
FEDERATION	CUSTOM_EMOJI_MAX_SIZE	"2000000"
FILESYSTEMS	FILESYSTEM_DRIVER	"local"
FILESYSTEMS	FILESYSTEM_CLOUD	"s3"
HASHING	BCRYPT_COST	"10"
HORIZON	HORIZON_PREFIX	"horizon-"
HORIZON	HORIZON_MEMORY_LIMIT	"64"
HORIZON	HORIZON_BALANCE_STRATEGY	"auto"
HORIZON	HORIZON_MIN_PROCESSES	"1"
HORIZON	HORIZON_MAX_PROCESSES	"20"
HORIZON	HORIZON_SUPERVISOR_MEMORY	"64"
HORIZON	HORIZON_SUPERVISOR_TRIES	"3"
HORIZON	HORIZON_SUPERVISOR_NICE	"0"
HORIZON	HORIZON_SUPERVISOR_TIMEOUT	"300"
HORIZON	HORIZON_DARKMODE	❌ false
IMAGE	IMAGE_DRIVER	"gd"
INSTANCE	INSTANCE_DESCRIPTION	"Pixelfed - Photo sharing for everyone"
INSTANCE	INSTANCE_CONTACT_FORM	❌ false
INSTANCE	INSTANCE_CONTACT_MAX_PER_DAY	"1"
INSTANCE	INSTANCE_DISCOVER_PUBLIC	❌ false
INSTANCE	EXP_LOOPS	❌ false
INSTANCE	INSTANCE_PUBLIC_HASHTAGS	❌ false
INSTANCE	INSTANCE_CONTACT_EMAIL	"victor@fedihost.co"
INSTANCE	INSTANCE_PUBLIC_LOCAL_TIMELINE	❌ false
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHED	
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_DROPOFF	100
INSTANCE	INSTANCE_NETWORK_TIMELINE_CACHE_MAX_HOUR_INGEST	6
INSTANCE	PAGE_404_HEADER	"Sorry, this page isn't available."
INSTANCE	PAGE_404_BODY	"The link you followed may be broken, or the page may have been removed. <a href="/">Go back to Pixelfed.</a>"
INSTANCE	PAGE_503_HEADER	"Service Unavailable"
INSTANCE	PAGE_503_BODY	"Our service is in maintenance mode, please try again later."
INSTANCE	BANNED_USERNAMES	""
INSTANCE	USERNAME_REMOTE_FORMAT	"@"
INSTANCE	USERNAME_REMOTE_CUSTOM_TEXT	""
INSTANCE	STORIES_ENABLED	✅ true
INSTANCE	RESTRICTED_INSTANCE	❌ false
INSTANCE	OAUTH_TOKEN_DAYS	"365"
INSTANCE	OAUTH_REFRESH_DAYS	"400"
INSTANCE	OAUTH_PAT_ENABLED	❌ false
INSTANCE	OAUTH_PAT_ID	""
INSTANCE	ENABLE_COVID_LABEL	✅ true
INSTANCE	COVID_LABEL_URL	"https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public"
INSTANCE	COVID_LABEL_ORG	"visit the WHO website"
INSTANCE	ENABLE_CONFIG_CACHE	✅ true
LDAP	LDAP_CONNECTION	"default"
LDAP	LDAP_LOGGING	✅ true
LDAP	LDAP_CACHE	❌ false
LOGGING	LOG_CHANNEL	"stderr"
LOGGING	LOG_LEVEL (stack)	"debug"
MAIL	MAIL_DRIVER	""
MAIL	MAIL_HOST	""
MAIL	MAIL_PORT	""
MAIL	MAIL_FROM_ADDRESS	"noreply-pix.canadiancivil.com@fedihost.co"
MAIL	MAIL_FROM_NAME	"Pixelfed"
MAIL	MAIL_ENCRYPTION	""
MEDIA	MEDIA_EXIF_DATABASE	❌ false
PIXELFED	ADMIN_DOMAIN	"pix.canadiancivil.com"
PIXELFED	APP_DOMAIN	"pix.canadiancivil.com"
PIXELFED	MEMORY_LIMIT	"1024M"
PIXELFED	OPEN_REGISTRATION	❌ false
PIXELFED	MAX_ACCOUNT_SIZE (KB)	"1000000"
PIXELFED	MAX_PHOTO_SIZE (KB)	"15000"
PIXELFED	MAX_AVATAR_SIZE (KB)	"2000"
PIXELFED	MAX_CAPTION_LENGTH	"500"
PIXELFED	MAX_BIO_LENGTH	"125"
PIXELFED	MAX_NAME_LENGTH	"30"
PIXELFED	MIN_PASSWORD_LENGTH	"8"
PIXELFED	MAX_ALBUM_LENGTH	"4"
PIXELFED	ENFORCE_EMAIL_VERIFICATION	❌ false
PIXELFED	IMAGE_QUALITY (1-100)	"80"
PIXELFED	ACCOUNT_DELETION	✅ true
PIXELFED	ACCOUNT_DELETE_AFTER	❌ false
PIXELFED	PF_ENABLE_CLOUD	✅ true
PIXELFED	PF_MAX_USERS	1000
PIXELFED	PF_OPTIMIZE_IMAGES	✅ true
PIXELFED	PF_OPTIMIZE_VIDEOS	✅ true
PIXELFED	PF_USER_INVITES	❌ false
PIXELFED	PF_USER_INVITES_TOTAL_LIMIT	"0"
PIXELFED	PF_USER_INVITES_DAILY_LIMIT	"0"
PIXELFED	PF_USER_INVITES_MONTHLY_LIMIT	"0"
PIXELFED	PF_MAX_COLLECTION_LENGTH	"100"
PIXELFED	MEDIA_TYPES	"image/jpeg,image/png,image/gif"
PIXELFED	LIMIT_ACCOUNT_SIZE	✅ true
PIXELFED	IMPORT_INSTAGRAM	✅ true
PIXELFED	IMPORT_INSTAGRAM_POST_LIMIT	"100"
PIXELFED	IMPORT_INSTAGRAM_SIZE_LIMIT	"5000"
PIXELFED	OAUTH_ENABLED	✅ true
PIXELFED	PF_BOUNCER_ENABLED	❌ false
PIXELFED	PF_MEDIA_FAST_PROCESS	✅ true
PIXELFED	PF_MEDIA_MAX_ALTTEXT_LENGTH	"1000"
PURIFY	RESTRICT_HTML_TYPES	BROKEN
QUEUE	QUEUE_DRIVER	"redis"
SESSION	SESSION_DRIVER	"redis"
SESSION	SESSION_LIFETIME	"86400"
SESSION	SESSION_DOMAIN	"pix.canadiancivil.com"
TRUSTEDPROXY	TRUST_PROXIES	"10.42.0.0/16"
========= END =========
```

Btw, I  really appreciate you looking into this, I know how busy your are right now.

**Comment by dansup** [comment]
@fishcharlie My apologies for the confusion, this is a deeper issue in our SearchService, I am refactoring it now and will update this issue when its shipped!

**Comment by dansup** [comment]
@fishcharlie @S0yKaf Can you update to the latest commits? I just merged a fix that should solve the search bug.

You may need to run `php artisan instance:actor` if you run into issues.

Will keep this open until you confirm its fixed on your side!

**Comment by S0yKaf** [comment]
@dansup Hey, I'm using https://github.com/jippi/docker-pixelfed and I've just tried setting the image to nightly-dev, it's still not fixed but I'm assuming it hasn't built the new version yet. 

I'll be able to test again after Christmas. Cheers and happy holidays!

**Comment by S0yKaf** [comment]
Hey @dansup sorry for the late follow-up. The issue is still going on. I think you might have reverted your fixes?
I'm assuming this was the commit that fixed the issue: https://github.com/pixelfed/pixelfed/commit/1d2f76c8e562cc7ce45899cc2d7a739015f9f5fa
And you may have reverted the fix in this commit: https://github.com/pixelfed/pixelfed/commit/85124aa6424c8a17736f0c31e2464d065630bbbb

Cheers.

**EDIT**

Please disregard the comment about the revert, it shouldn't have affected what you did in  https://github.com/pixelfed/pixelfed/commit/1d2f76c8e562cc7ce45899cc2d7a739015f9f5fa

**Comment by S0yKaf** [comment]
Important note, My DB has this "patch" applied
```sql
alter table media alter column caption drop not null;
```
This was the suggested fix for https://github.com/pixelfed/pixelfed/issues/5217

**Comment by arthurcaccavo** [comment]
I'm having this issue on gram.social and pixey.org also

example:
https://pixey.org/i/web/profile/785493211116484317
https://gram.social/i/web/profile/784939081054493110
https://pixelfed.social/i/web/profile/784874902343624621

EDIT: one post (there are more) started showing on gram.social but the profile information (post count and followers/ing is still wrong)

**Comment by Casuallynoted** [comment]
Also getting this issue consistently on https://pixelfed.casually.cat, seems to have something to do with the worker as:php artisan queue:flushphp artisan queue:restartSeems to help fix it temporarily (thank you to Colto for that advice!)On Jan 16, 2025, at 8:19 AM, Arthur Caccavo ***@***.***> wrote:﻿
I'm having this issue on gram.social and pixey.org also
example:
https://pixey.org/i/web/profile/785493211116484317
https://gram.social/i/web/profile/784939081054493110
https://pixelfed.social/i/web/profile/784874902343624621

**Comment by S0yKaf** [comment]
@Casuallynoted 
>php artisan queue:flush php artisan queue:restart Seems to help fix it temporarily

This did not fix the issue for me.

**Comment by mlkr4** [comment]
As a user I have basically the same issue from smaller instances, federation doesnt work both ways between pixelfed.social and [witter.cz, pixelfed.cz], contacted both admins, both told me that federation towards pixelfed.social works.

**Comment by CptCurk** [comment]
Hello, 
I kinda got the problem, it's not bringin profil pictures, and showing only new posts. As I created my instance 2 days agos, I've only 10 pictures on the global feed. Quite frustrating !

Do you have some ideas how to solve that and to make it work ?

**Comment by shleeable** [comment]
Hello, this looks to be talking about "back filling", and the problem with accounts previous posts not being replicated.

I will add this to the roadmap issue
