### ISSUE TITLE
<title> info is not updated

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#603]
`<title>` tag is important when getting a preview on other web services.
Unfortunately, Pixelfed currently doesn't update it.
For example, see [this post](https://pixelfed.social/p/Groosha/20329), it has 8 likes while title says `"0 likes,       comments"`, so previews show incorrect info.

**Comment by dansup** [comment]
Fixed in 25a3d142

**Comment by MasterGroosha** [comment]
@dansup I'm afraid it's not fully fixed :) 
OpenGraph title is still invalid.

![default](https://user-images.githubusercontent.com/2780044/49500505-e6b6a800-f881-11e8-858c-c88fed396ba1.png)

**Comment by dansup** [comment]
@MasterGroosha Good find! Will be fixed in an upcoming commit.

**Comment by amal-fi-haq** [comment]
Just wanted to confirm that og:title is still reporting incorrectly.

URL: https://pxlfd.me/p/amal/820 

Embed Content: `<meta property="og:title" content="amal posted a photo: 0 likes,  comments" />`

**Comment by dansup** [comment]
The latest commits have the ```og:title``` replaced with "A post by {username}". Since Facebook and Twitter cache the counts, there is no real point in adding them.

**Comment by amal-fi-haq** [comment]
Perfect. Thanks!
