### ISSUE TITLE
[Bug]: remove of line-breaks from non-pixelfed posts is leading to broken links and hashtags

### ISSUE THREAD

**Issue by joergi** [pixelfed/pixelfed#6064]
### Description

If you post on other Fediverse plattforms like Mastodon a text with line breaks, the Pixelfed server is removing the line-break.

This is leading to the issue, that the text is merged all together. This means links and Hashtags will be broken.
As the majority of Fediverse users are not (yet?) Pixelfed users, but Mastodon users, this behavior should be fixed.

Original post coming from Mastodon: 
https://chaos.social/@joergi/114836718329345106
This is how the Mastodon post looks in the browser:
![Screenshot_20250712-073359.png](https://github.com/user-attachments/assets/dae82f62-dd30-476b-b456-522d28433568)

  
  

This is, how looks in the browser on Pixelfed:    
https://punk.photos/i/web/post/849398838362864384
<img width="1224" height="2700" alt="Image" src="https://github.com/user-attachments/assets/3d06f029-2677-49d9-a28e-ae806ddf15f6" />
   
  
This is, how it looks in the official pixelfed app.
<img width="1224" height="2700" alt="Image" src="https://github.com/user-attachments/assets/fb6ed36d-ab78-4e2c-9f3a-b24fb50f2ea0" />
  
  
This is how it looks in Pixeldroid
<img width="1224" height="2700" alt="Image" src="https://github.com/user-attachments/assets/a82f8daa-9797-4160-a2e4-c221ec8e0b5e" />
  
  
This is how it looks in Pixelix (Android), which is then changing the links. 
<img width="1224" height="2700" alt="Image" src="https://github.com/user-attachments/assets/5bb52aa2-0dcc-4768-90c9-c65cdc41e092" />

### Steps to reproduce

1. Write a post on Mastodon wirh line-breaks.
2. Follow the Mastodon user with a Pixelfed user
3. Look on Pixelfed and see that the links and hashtags are broken

Solution:
When the line-break is removed, just add a space instead. I was already looking at the code, but I could not find where this happens

### Pixelfed version

 v0.12.5
Update: still happening with v0.12.6

### Acknowledgements

Yes

**Comment by joergi** [comment]
I'm happy if someone gives me a hint, where around in the code the removal happens, than i can maybe change it myself

**Comment by xundeenergie** [comment]
> I'm happy if someone gives me a hint, where around in the code the removal happens, than i can maybe change it myself

I don't know the code...

But posts from pixelfed-instances are rendered well.

Does Pixelfed use json-ld?
Maybe it happens there, when the delivered json gets converted from json to json-ld.

I also think, it could happen somwhere after reading the original message from Inbox.

I can write out the original json messages from other Servers on my friendica instance. This must be the exactly same on pixelfed. Only the receiver is a pixelfed-accound instead of a friendica account.

Just to compare, what pixelfed sends, and what friendica, mastodon send.

I think, pixelfed uses another format for the caption as friendica/mastodon do, and does parsing for the pixelfed format, which breaks friendica/mastodon postings.

**Comment by joergi** [comment]
I updated the ticket, still happening with v0.12.6

**Comment by xundeenergie** [comment]
Can confirm this

> I updated the ticket, still happening with v0.12.6

**Comment by joergi** [comment]
@dansup fixed this already, it's just not release since September.
see his comment on Mastodon here: https://mastodon.social/@dansup/115207421170939248 

Commit: https://github.com/pixelfed/pixelfed/commit/f37661e945891cd4c52ef19a21e22d3190876701 

I still don't understand why line breaks needs to be removed, but that's a complete other topic ...  I'm just happy if the bug fix will be released.

**Comment by joergi** [comment]
This is fixed, thx @dansup

**Comment by xundeenergie** [comment]
Sorry it is not fixed für Postings from Friendica.

Posted something yesterday and in Pixelfed stll missing linebreaks... 

This from friendica 
https://soc.schuerz.at/display/4edd2508-146a-1379-b938-1a2086790927

Looks this in my pixelfed

<img width="1063" height="968" alt="Image" src="https://github.com/user-attachments/assets/58146ad4-73f8-4f2b-b07b-dddaa529322e" />

Please reopen this bug!!

**Comment by joergi** [comment]
@xundeenergie - I saw @dansup was reopening the ticket.
But the main bug report was about that the remove of the line breaks was breaking links and hashtags.
In your example it looks okay to me, just no line breaks, which is the design of Pixelfed I fear (I would also prefer to keep them)

Not sure what @dansup is thinking about it: is that wanted, that all the line breaks are removed?
