### ISSUE TITLE
Timeline shows image without filter

### ISSUE THREAD

**Issue by MasterGroosha** [pixelfed/pixelfed#635]
When I open my timeline, I see posted image without any filters:
![default](https://user-images.githubusercontent.com/2780044/49866390-b4c0bb00-fe18-11e8-9f6a-8a0cb7a48aa7.png)

However, when I open it separately, an applied filter is shown:
![default](https://user-images.githubusercontent.com/2780044/49866415-c99d4e80-fe18-11e8-9453-f36f424a8680.png)

I hope this is not a feature :)

**Comment by dansup** [comment]
@MasterGroosha This has been fixed in the latest commits.

**Comment by MasterGroosha** [comment]
Unfortunately this is not fixed :(
Post (showing part of it):
![изображение](https://user-images.githubusercontent.com/2780044/54921088-ec5df980-4f15-11e9-8d55-dc6231332cfd.png)

Discover (no filter seen):
![изображение](https://user-images.githubusercontent.com/2780044/54921111-fed83300-4f15-11e9-9963-eb43dbd12064.png)

If link to post is sent somewhere, e.g. Telegram (no filter seen):
![изображение](https://user-images.githubusercontent.com/2780044/54921134-11eb0300-4f16-11e9-8340-18d90243dda9.png)

Even Mastodon shows image without filter:
![изображение](https://user-images.githubusercontent.com/2780044/54921291-78702100-4f16-11e9-904b-b3d510015ac6.png)

**Comment by trwnh** [comment]
@MasterGroosha see #730 for that -- filters are applied via CSS and not via processing the image itself. This allows for potentially updating the filter in the future.
