### ISSUE TITLE
Unable to upload avatar on pixelfed.social

### ISSUE THREAD

**Issue by pgpattison** [pixelfed/pixelfed#637]
Steps to reproduce:
 - Go to Account Settings, click Change Profile Photo
 - Click Browse... button, select image to upload
 - "Upload" button remains inactive (pale blue)
 - When I click the Upload button (or anywhere else), the dialogue simply closes without uploading anything.

Identical behavior on three systems: mobile device running Android 5.1.1, laptop running Xubuntu 18.04, and desktop running Debian 9 (using current version of Firefox on all three)

**Comment by dansup** [comment]
@pgpattison That is caused by an invalid mime type or an image that exceeds the avatar file size limit. I will add an error warning so you know why it failed.

**Comment by dansup** [comment]
@pgpattison I will investigate.

**Comment by dansup** [comment]
@pgpattison It should be fixed now, can you try again?

**Comment by dansup** [comment]
I will re-open this issue when it's reproducible, it should be fixed now.

**Comment by pgpattison** [comment]
No change. Still unable to upload user profile image.

User profile is PalmerAnimates (if that helps)
