### ISSUE TITLE
Image rotates upon upload?

### ISSUE THREAD

**Issue by ghost** [pixelfed/pixelfed#75]
Image display in correct orientation in my phone library & initially when viewing the post however its rotated 90 degrees upon viewing from my profile (and remains rotated after clicking on the image to view it indevidually)

Profile is https://pixelfed.social/Satsu and I’ve got a screen recording of this happening if thats useful to you

**Comment by Zatnosk** [comment]
This sounds very much like the image is stored without taking care of the Exif orientation tag.

**Comment by ghost** [comment]
as far as I can tell this issue is account specific, other people’s images are displaying in the correct orientation as far as I can tell & all of mine are rotated. 

It could be something on my end? But I havent had this problem when uploading to mastodon or instagram, and the second photo i uploaded was specifically one i’d posted elsewhere with no problems

**Comment by arjenpdevries** [comment]
Another example: https://pixelfed.social/p/arjen/65

BTW, Tusky has this problem too. 
Mastodon web app does it right though.

**Comment by Sigafoos** [comment]
[Another one](https://pixelfed.social/p/dconley/366). It's definitely an EXIF issue.

**Comment by kpcyrd** [comment]
@Zatnosk is correct, EXIF metadata is stripped for privacy reasons (you might upload your physical location by accident if this is not done).

https://github.com/dansup/pixelfed/blob/7313bca4e69f2cf5c515c2f6ac5f21b2b986a5ab/config/image-optimizer.php#L16-L20

This seems to strip the orientation tag as well. Since not all pictures depend on a orientation tag only some of them have incorrect rotation.

**Comment by dansup** [comment]
Fixed in b437b627

**Comment by arjenpdevries** [comment]
Maybe not fully fixed.

Uploaded same photo again.

Correct when opening profile:
https://pixelfed.social/arjen

Wrong when looking at post page:
https://pixelfed.social/p/arjen/1661

Just noticed:
On desktop both work, on phone one has a rotated photo:

**Comment by armeris** [comment]
I'm still experiencing this issue.
I have uploaded a photo from my mobile (android - firefox) and it appears rotated: https://pixelfed.social/p/Armeris/2026

**Comment by koehn** [comment]
I'm also experiencing this issue. [This image](https://pixelfed.koehn.com/p/bkoehn/14) displays correctly on my phone, but displays upside down in FF 63.

**Comment by dansup** [comment]
@koehn When you upload an image, it takes a few seconds for the image optimize job to process and properly orientate the image.

**Comment by ghost** [comment]
Hello,

@dansup it's only partially resolved, when I upload a photo took in vertical position the preview still show it rotated 90 degrees left.

<img width="514" alt="Screenshot 2019-04-08 at 23 37 31" src="https://user-images.githubusercontent.com/41020854/55759098-e3fad800-5a58-11e9-96d7-d34c66f95301.png">

The filters previews are also deformed. However, as you can see here: https://pics.mental.af/p/mathias/20984964078243840, when the post is created the photo is correctly rotated.

**Comment by martyav** [comment]
Recently started using PixelFed, and started having the same problem from a batch of photos I was about to post.
