### ISSUE TITLE
Usernames with symbols are not searchable

### ISSUE THREAD

**Issue by Chaos99** [pixelfed/pixelfed#784]
For some reason, my account @Chaos_99@pixelfed.social can not be found with the search on pixelfed.social. It can be found on other federated servers like mastodon.social.
It doesn't matter if I search for the full name with instance, just the name or with/without the '@' in front.
This is both true for me searching for myself as well as friends searching for me. 

I tried to search for other accounts and found that some are also not discover-able. 
Common issue seems to be a special character like '_' or '-' in the name.

**Comment by Chaos99** [comment]
Must be more than the underscore. At least also the dash character: Try searching for user 'Jean-Paul' or 'Ben-J'

**Comment by carlydotwebsite** [comment]
Additional note to maybe look into while investigating—local profiles without underscores or other non-letter/number characters seem to appear twice in search.

**Comment by dansup** [comment]
@Chaos99 The search does not support remote profile discovery yet, this will be fixed soon!

**Comment by carlydotwebsite** [comment]
@dansup weirdly I was able to find and pull up a remote profile for @carly@kitty.town (my mastodon account) by searching "carly" to search for my own profile :|a

**Comment by dansup** [comment]
@cmho Pixelfed search can't discover a new profile like other implementations can by pasting the url to the profile, but if a remote account is already known by the instance it will appear in results. That kitty.town account must have interacted with pixelfed.social already!

**Comment by Chaos99** [comment]
@dansup Can you define 'remote profile'? My account 'Chaos_99' as well as that of 'Jean-Paul' are local to pixelfed.social.

**Comment by Chaos99** [comment]
Interestingly, today on pixelfed.social I could enter "crossg" into the search field and find @crossgolf_rebel@pixelfed.de in the results.
Searching for mindaffecter_ef@pixlfd.me didn't work.
Search for myself also didn't work as reported above.

**Comment by Chaos99** [comment]
In 0.8.5 the search interface is reworked. But the problem still persists.
Neither myself (probably because of the underscore) nor profiles from other instances can be searched.
(And without this, I don't know if profiles from other instances can be followed at all.)

**Comment by dansup** [comment]
Fixed in #1136

**Comment by Chaos99** [comment]
I'd like to re-open this ticket. According to the milestone planning, this should have been active at 0.9.0, but my account still can't be searched and pixelfed.social is on 0.9.2.

I also see this for the account @mindaffecter_ef@pxlfd.me, but as this is from another instance, this might be another issue.

I DO see that other accounts with '_' are returned by the search engine, so the issues might be something different.

**Comment by trwnh** [comment]
looks working to me https://pixelfed.social/i/results?q=chaos_99

**Comment by Chaos99** [comment]
![image](https://user-images.githubusercontent.com/582663/57582652-c8f00d80-74c7-11e9-8087-2ca42f0f7533.png)

Doesn't work for me or two other people I've asked.

**Comment by muesli** [comment]
@Chaos99 Maybe it's just not finding yourself now? I can find your account on pixelfed.social now, fwiw. I can also not find myself with my own account.

**Comment by trwnh** [comment]
Yeah, looks like your own account isn't returned via search

**Comment by Chaos99** [comment]
`Yeah, looks like your own account isn't returned via search`
I'd like to add this to the bug report then. Seeing your profile as it appears to others (including you showing up in searches/discovers) is an important verification tool.

I've asked the other guys that can't find my profile to either comment here or send me screenshots of their searches.

**Comment by dansup** [comment]
@Chaos99 Your own profile will not appear in search results.
